# Generated by Django 3.2 on 2022-04-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220416_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='e_mail',
            field=models.CharField(max_length=20, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='gender',
            field=models.CharField(max_length=5, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='password',
            field=models.CharField(max_length=13, verbose_name='PW'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='user',
            field=models.CharField(max_length=10, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='user_name',
            field=models.CharField(max_length=5, verbose_name='사용자'),
        ),
    ]
