# Generated by Django 3.2 on 2022-04-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220416_1540'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_list',
            table='user_list',
        ),
    ]
