# Generated by Django 3.2 on 2022-04-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_list_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_list',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='user_list',
            name='age',
            field=models.IntegerField(null=True, verbose_name='나이'),
        ),
    ]
